<?php
// Tableau de prénoms :
$tabPrenoms = array(
  "Abel",
  "Achille",
  "Adeline",
  "Adelphe",
  "Adèle",
  "Agathe",
  "Agnès",
  "Aimé",
  "Aimée",
  "Alain",
  "Alban",
  "Albert",
  "Alexandre",
  "Alexis",
  "Alice",
  "Alida",
  "Alix",
  "Alphonse",
  "Amandine",
  "Ambroise",
  "Amour",
  "Amédée",
  "André",
  "Angèle",
  "Anicet",
  "Anne",
  "Anselme",
  "Anthelme",
  "Antoine",
  "Apollinaire",
  "Apolline",
  "Aristide",
  "Armand",
  "Armel",
  "Arnaud",
  "Arsène",
  "Aubin",
  "Aude",
  "Audrey",
  "Augustin",
  "Aymar",
  "Banard",
  "Barbara",
  "Barnabé",
  "Barthélémy",
  "Baudoin",
  "Benjamin",
  "Benoît",
  "Benoît-Joseph",
  "Bernadette",
  "Bernard",
  "Bernardin",
  "Bertille",
  "Bertrand",
  "Bienvenue",
  "Blaise",
  "Blandine",
  "Boris",
  "Brice",
  "Brigitte",
  "Bruno",
  "Béatrice",
  "Bénédicte",
  "Bérenger",
  "Camille",
  "Carine",
  "Casimir",
  "Cassandre",
  "Catherine",
  "Chantal",
  "Charles",
  "Charlotte",
  "Christian",
  "Christine",
  "Christophe",
  "Claire",
  "Clarisse",
  "Claude",
  "Clotilde",
  "Clémence",
  "Clément",
  "Colette",
  "Constant",
  "Constantin",
  "Crépin",
  "Cyprien",
  "Cyrille",
  "Cécile",
  "Céline",
  "Côme",
  "Damien",
  "Daniel",
  "David",
  "Davy",
  "Delphine",
  "Denis",
  "Denise",
  "Diane",
  "Didier",
  "Dimitri",
  "Dominique",
  "Donald",
  "Donatien",
  "Défunts",
  "Désiré",
  "Edith",
  "Edmond",
  "Edouard",
  "Edwige",
  "Elisabeth",
  "Elisée",
  "Ella",
  "Elodie",
  "Emeline",
  "Emile",
  "Emilie",
  "Emma",
  "Eric",
  "Estelle",
  "Etienne",
  "Eté",
  "Eugènie",
  "Evrard",
  "Eymard",
  "Fabrice",
  "Ferdinand",
  "Fernand",
  "Fiacre",
  "Fidèle",
  "Firmin",
  "Fleur",
  "Flora",
  "Florence",
  "Florent",
  "Florentin",
  "François",
  "Françoise",
  "Frédéric",
  "Fulbert",
  "Félicité",
  "Félix",
  "Gabin",
  "Gaston",
  "Gatien",
  "Gautier",
  "Gaétan",
  "Gaël",
  "Geneviève",
  "Geoffroy",
  "Georges",
  "Germain",
  "Germaine",
  "Ghislain",
  "Gilbert",
  "Gildas",
  "Gilles",
  "Gisèle",
  "Gontran",
  "Grégoire",
  "Guillaume",
  "Guy",
  "Guénolé",
  "Gwladys",
  "Gérald",
  "Gérard",
  "Géraud",
  "Habib",
  "Henri",
  "Hermann",
  "Hervé",
  "Hippolyte",
  "Honorine",
  "Honoré",
  "Hubert",
  "Hugues",
  "Hyacinthe",
  "Hélène",
  "Ida",
  "Ignace",
  "Igor",
  "Ingrid",
  "Innocent",
  "Inès",
  "Irène",
  "Irénée",
  "Isabelle",
  "Isidore",
  "Jacqueline",
  "Jacques",
  "Jean",
  "Jean Eudes",
  "Jean-Baptiste",
  "Jean-Marie",
  "Joachin",
  "Joseph",
  "Joël",
  "Jude",
  "Judith",
  "Jules",
  "Julie",
  "Julien",
  "Julienne",
  "Juliette",
  "Juste",
  "Justin",
  "Justine",
  "Jérémie",
  "Jérôme",
  "Kévin",
  "Landry",
  "Larissa",
  "Laurent",
  "Lazare",
  "Louis",
  "Louise",
  "Luc",
  "Lucie",
  "Lucien",
  "Lydie",
  "Léa",
  "Léger",
  "Léocadie",
  "Léon",
  "Léonce",
  "Marc",
  "Marcel",
  "Marcelle",
  "Marcellin",
  "Marguerite",
  "Marie",
  "Marie-Madeleine",
  "Mariette",
  "Marina",
  "Marius",
  "Marthe",
  "Martial",
  "Martin",
  "Martine",
  "Martinien",
  "Mathilde",
  "Matthias",
  "Matthieu",
  "Maurice",
  "Maxime",
  "Michel",
  "Modeste",
  "Monique",
  "Médard",
  "Mélaine",
  "Nadège",
  "Narcisse",
  "Natacha",
  "Nathalie",
  "Nativité",
  "Nestor",
  "Nicolas",
  "Nina",
  "Ninon",
  "Norbert",
  "Noël",
  "Odette",
  "Odile",
  "Odilon",
  "Olive",
  "Olivier",
  "Pacôme",
  "Parfait",
  "Pascal",
  "Paterne",
  "Patrice",
  "Paul",
  "Paule",
  "Pauline",
  "Philippe",
  "Pierre",
  "Prisca",
  "Prosper",
  "Prudence",
  "Présentation",
  "Pélagie",
  "Quentin",
  "Raoul",
  "Raymond",
  "Raïssa",
  "Reine",
  "Renaud",
  "René",
  "Richard",
  "Robert",
  "Rodrigue",
  "Roger",
  "Roland",
  "Rolande",
  "Romain",
  "Romaric",
  "Romuald",
  "Roméo",
  "Rosalie",
  "Rose",
  "Roseline",
  "Rosine",
  "Régis",
  "Rémi",
  "Sabine",
  "Samson",
  "Sandrine",
  "Saturnin",
  "Sauveur",
  "Serge",
  "Sidoine",
  "Silvère",
  "Solange",
  "Sophie",
  "Stanislas",
  "Sylvain",
  "Sylvestre",
  "Sylvie",
  "Sébastien",
  "Sévrin",
  "Tanguy",
  "Tatiana",
  "Thibaud",
  "Thibault",
  "Thierry",
  "Thomas",
  "Thècle",
  "Théodore",
  "Théophile",
  "Thérèse",
  "Ulrich",
  "Urbain",
  "Valentin",
  "Valérie",
  "Venceslas",
  "Victor",
  "Victorien",
  "Vincent",
  "Viviane",
  "Vivien",
  "Véronique",
  "Wilfried",
  "Xavier",
  "Xavière",
  "Yves",
  "Yvette",
  "Zita"
);

// Tableau des noms :
$tabNoms = array(
  "ADAM",
  "ANDRE",
  "ANTOINE",
  "ARNAUD",
  "AUBERT",
  "AUBRY",
  "BAILLY",
  "BARBIER",
  "BARON",
  "BARRE",
  "BARTHELEMY",
  "BENARD",
  "BENOIT",
  "BERGER",
  "BERNARD",
  "BERTIN",
  "BERTRAND",
  "BESSON",
  "BLANC",
  "BLANCHARD",
  "BONNET",
  "BOUCHER",
  "BOUCHET",
  "BOULANGER",
  "BOURGEOIS",
  "BOUVIER",
  "BOYER",
  "BRETON",
  "BRUN",
  "BRUNET",
  "CARLIER",
  "CARON",
  "CARPENTIER",
  "CARRE",
  "CHARLES",
  "CHARPENTIER",
  "CHAUVIN",
  "CHEVALIER",
  "CHEVALLIER",
  "CLEMENT",
  "COLIN",
  "COLLET",
  "COLLIN",
  "CORDIER",
  "COUSIN",
  "DA SILVA",
  "DANIEL",
  "DAVID",
  "DELAUNAY",
  "DENIS",
  "DESCHAMPS",
  "DUBOIS",
  "DUFOUR",
  "DUMAS",
  "DUMONT",
  "DUPONT",
  "DUPUIS",
  "DUPUY",
  "DURAND",
  "DUVAL",
  "ETIENNE",
  "FABRE",
  "FAURE",
  "FERNANDEZ",
  "FLEURY",
  "FONTAINE",
  "FOURNIER",
  "FRANCOIS",
  "GAILLARD",
  "GARCIA",
  "GARNIER",
  "GAUTHIER",
  "GAUTIER",
  "GERARD",
  "GERMAIN",
  "GILBERT",
  "GILLET",
  "GIRARD",
  "GIRAUD",
  "GRONDIN",
  "GUERIN",
  "GUICHARD",
  "GUILLAUME",
  "GUILLOT",
  "GUYOT",
  "HAMON",
  "HENRY",
  "HERVE",
  "HOARAU",
  "HUBERT",
  "HUET",
  "HUMBERT",
  "JACOB",
  "JACQUET",
  "JEAN",
  "JOLY",
  "JULIEN",
  "KLEIN",
  "LACROIX",
  "LAMBERT",
  "LAMY",
  "LANGLOIS",
  "LAPORTE",
  "LAURENT",
  "LE GALL",
  "LE GOFF",
  "LE ROUX",
  "LEBLANC",
  "LEBRUN",
  "LECLERC",
  "LECLERCQ",
  "LECOMTE",
  "LEFEBVRE",
  "LEFEVRE",
  "LEGER",
  "LEGRAND",
  "LEJEUNE",
  "LEMAIRE",
  "LEMAITRE",
  "LEMARCHAND",
  "LEMOINE",
  "LEROUX",
  "LEROY",
  "LEVEQUE",
  "LOPEZ",
  "LOUIS",
  "LUCAS",
  "MAILLARD",
  "MALLET",
  "MARCHAL",
  "MARCHAND",
  "MARECHAL",
  "MARIE",
  "MARTIN",
  "MARTINEZ",
  "MARTY",
  "MASSON",
  "MATHIEU",
  "MENARD",
  "MERCIER",
  "MEUNIER",
  "MEYER",
  "MICHAUD",
  "MICHEL",
  "MILLET",
  "MONNIER",
  "MOREAU",
  "MOREL",
  "MORIN",
  "MOULIN",
  "MULLER",
  "NICOLAS",
  "NOEL",
  "OLIVIER",
  "PARIS",
  "PASQUIER",
  "PAYET",
  "PELLETIER",
  "PEREZ",
  "PERRET",
  "PERRIER",
  "PERRIN",
  "PERROT",
  "PETIT",
  "PHILIPPE",
  "PICARD",
  "PICHON",
  "PIERRE",
  "POIRIER",
  "POULAIN",
  "PREVOST",
  "REMY",
  "RENARD",
  "RENAUD",
  "RENAULT",
  "REY",
  "REYNAUD",
  "RICHARD",
  "RIVIERE",
  "ROBERT",
  "ROBIN",
  "ROCHE",
  "RODRIGUEZ",
  "ROGER",
  "ROLLAND",
  "ROUSSEAU",
  "ROUSSEL",
  "ROUX",
  "ROY",
  "ROYER",
  "SANCHEZ",
  "SCHMITT",
  "SCHNEIDER",
  "SIMON",
  "TESSIER",
  "THOMAS",
  "VASSEUR",
  "VIDAL",
  "VINCENT",
  "WEBER"
);

// Tableau des types de voie :
$tabTypeVoies = array(
  "allée",
  "avenue",
  "boulevard",
  "chemin",
  "grand-route",
  "grand-rue",
  "impasse",
  "passage",
  "place",
  "quai",
  "route",
  "rue",
  "ruelle",
  "venelle",
  "voie"
);

// Tableau des noms de voie :
$tabNomsVoies = array(
"Adrien Hébrard",
"Adrienne",
"Adrienne Lecouvreur",
"Albert Bartholomé",
"Albert Ier de Monaco",
"Albert de Mun",
"Alexandre Vialatte",
"Alphand",
"Alphonse XIII",
"Alquier Debrousse",
"Ambroise Rendu",
"Anatole France",
"André Breton",
"André Rivoire",
"Anne de Beaujeu",
"Annibal",
"Antoine Loubeyre",
"Armand Rousseau",
"Arthur Honegger",
"Aubry",
"Auguste Chabrières",
"Barbey d'Aurevilly",
"Bauer",
"Beaucour",
"Beauharnais",
"Benoît Frachon",
"Bergère",
"Berryer",
"Bertie Albrecht",
"Bertrand",
"Blaise Cendrars",
"Blanche",
"Bosquet",
"Boudon",
"Boutroux",
"Brunetière",
"Bugeaud",
"Caffieri",
"Carnot",
"Cartellier",
"Champagne",
"Chantemesse",
"Chaptal",
"Charles Floquet",
"Charles Girault",
"Charles Godon",
"Charles Risler",
"Charles de Foucauld",
"Christian Pineau",
"Claude Regaud",
"Claude Vellefaux",
"Condorcet",
"Constant Coquelin",
"Corentin Cariou",
"Courteline",
"Célestin Hennion",
"César Caire",
"Daniel Lesueur",
"Darius Milhaud",
"Daumesnil",
"David Weill",
"Debergue",
"Debidour",
"Delcassé",
"Delecourt",
"Denfert Rochereau",
"Despréaux",
"Diane de Poitiers",
"Dode de La Brunerie",
"Dorian",
"Dulcie September",
"Dupleix",
"Duquesne",
"Dutuit",
"Edison",
"Edmond Michelet",
"Edmond Rostand",
"Edward Tuck",
"Edwige Feuillère",
"El Salvador",
"Emmanuel Levinas",
"Erlanger",
"Ernest Denis",
"Ernest Renan",
"Ernest Reyer",
"Eugène Beaudouin",
"Eugène Claudius Petit",
"Falguière",
"Federico Garcia Lorca",
"Ferdinand Brunot",
"Ferdinand Buisson",
"Ferdousi",
"Fernand Mourlot",
"Flora Tristan",
"Foch",
"Fortunée",
"Francis Poulenc",
"Franklin D. Roosevelt",
"Franz Liszt",
"François Ier",
"Frochot",
"Frédéric Le Play",
"Fréhel",
"Frémiet",
"Félicien Rops",
"Félix Faure",
"Félix d'Hérelle",
"Félix Éboué",
"Gabriel",
"Gabriel Péri",
"Gabrielle d'Estrées",
"Gambetta",
"Gaston Bachelard",
"George V",
"Georges Bernanos",
"Georges Berry",
"Georges Besse",
"Georges Guillaumin",
"Georges Lafenestre",
"Georges Lafont",
"Georges Mandel",
"Georges Recipon",
"Georges Risler",
"Georges Rouault",
"Gordon Bennett",
"Gourgaud",
"Gustave Eiffel",
"Gustave V de Suède",
"Henri Martin",
"Henry Dunant",
"Hoche",
"Hussein 1er de Jordanie",
"Ibsen",
"Ingres",
"Jean Aicard",
"Jean Jaurès",
"Jean Moulin",
"Jean Paulhan",
"Jean Sablon",
"Joseph Bouvard",
"Joseph Bédier",
"Jules Janin",
"Jules Sandeau",
"Jules Supervielle",
"Junot",
"Kellermann",
"Kléber",
"Lamoricière",
"Lannes",
"Ledru Rollin",
"Lefebvre",
"Louis Aragon",
"Louis Barthou",
"Louise Labé",
"Lucien Descaves",
"Léon Bollée",
"Léon Bourgeois",
"Léon Gaumont",
"Léon Heuzey",
"Léopold II",
"Mac Mahon",
"Macdonald",
"Malesherbes",
"Marbeau",
"Marc Chagall",
"Marc Sangnier",
"Marceau",
"Marcel Doret",
"Marcel Jambenoire",
"Marcel Proust",
"Marguerite Yourcenar",
"Maria Callas",
"Marie Laurent",
"Marius Barroux",
"Masséna",
"Mathurin Moreau",
"Matignon",
"Maurice Baumont",
"Maurice Ravel",
"Maurice d'Ocagne",
"Milleret de Brou",
"Moderne",
"Molière",
"Montaigne",
"Montmartre",
"Morland",
"Mortemart",
"Mortier",
"Mozart",
"Murat",
"Myron Herrick",
"Ney",
"Niel",
"Nijinski",
"Octave Gréard",
"Ornano",
"Parmentier",
"Pasteur",
"Paul Adam",
"Paul Appell",
"Paul Deschanel",
"Paul Doumer",
"Paul Déroulède",
"Paul Vaillant Couturier",
"Percier",
"Pereire",
"Pernette du Guillet",
"Perrichont",
"Pershing",
"Philippe Auguste",
"Pierre Ier de Serbie",
"Pierre Lazareff",
"Pierre Loti",
"Pierre Masse",
"Pierre Mendès France",
"Pierre Mollaret",
"Pierre de Coubertin",
"Pilâtre de Rozier",
"Poissonnière",
"Poniatowski",
"Prudhon",
"Périphérique",
"Rachel",
"Raphaël",
"Rapp",
"Raspail",
"Raymond Poincaré",
"Reille",
"René Boylesve",
"René Coty",
"René Fonck",
"Richard Lenoir",
"Richard Wallace",
"Rimski Korsakov",
"Rodenbach",
"Romain Rolland",
"Royale",
"Saint Denis",
"Saint Germain",
"Saint Jacques",
"Saint John Perse",
"Saint Marcel",
"Saint Martin",
"Saint Michel",
"Samuel Beckett",
"Soult",
"Suchet",
"Sérurier",
"Thierry de Martel",
"Thomy Thierry",
"Valentin Abeille",
"Verhaeren",
"Verte",
"Victor",
"Vincent Auriol",
"Voltaire",
"d'Andrézieux",
"d'Angoulême",
"d'Austerlitz",
"d'Eylau",
"d'Hauteville",
"d'Italie",
"d'Ivry",
"d'Iéna",
"de Beauté",
"de Bercy",
"de Boufflers",
"de Bouvines",
"de Breteuil",
"de Buci",
"de Camoëns",
"de Ceinture du Lac Inférieur",
"de Ceinture du Lac Supérieur",
"de Chabrol",
"de Champaubert",
"de Choisy",
"de Clichy",
"de Corbera",
"de Crussol",
"de Flandre",
"de Fontainebleau",
"de Fontenay",
"de France",
"de Friedland",
"de Gravelle",
"de Gênes",
"de Joinville",
"de La Bourdonnais",
"de Lamballe",
"de Laumière",
"de Londres",
"de Longchamp",
"de Lowendal",
"de Madrid à Neuilly",
"de Magenta",
"de Malakoff",
"de Marigny",
"de Mazagran",
"de Messine",
"de Montespan",
"de Montmorency",
"de Neuilly",
"de New York",
"de Nogent",
"de Norvège",
"de Paris",
"de Phalsbourg",
"de Pologne",
"de Port Royal",
"de Provence",
"de Pusy",
"de Péterhof",
"de Rouvray",
"de Saint Cloud",
"de Saint Mandé",
"de Saint Maurice",
"de Saint Ouen",
"de Salonique",
"de Saxe",
"de Selves",
"de Suffren",
"de Suresnes à Bagatelle",
"de Ségur",
"de Taillebourg",
"de Tourville",
"de Trévise",
"de Valois",
"de Verdun",
"de Versailles",
"de Verzy",
"de Villars",
"de Villiers",
"de Vivaldi",
"de Wagram",
"de l'Abbé Roussel",
"de l'Alma",
"de l'Avenir",
"de l'Ermitage",
"de l'Espérance",
"de l'Hippodrome",
"de l'Industrie",
"de l'Observatoire",
"de l'Odéon",
"de l'Opéra",
"de l'École de Joinville",
"de la Belle Gabrielle",
"de la Chapelle",
"de la Comtesse de Ségur",
"de la Conservation",
"de la Croix Catelan",
"de la Dame Blanche",
"de la Deuxième D. B.",
"de la Ferme de la Faisanderie",
"de la Garance",
"de la Grande Armée",
"de la Mairie",
"de la Motte Picquet",
"de la Muette",
"de la Patte d'Oie",
"de la Porte Brancion",
"de la Porte Brunet",
"de la Porte Chaumont",
"de la Porte Didot",
"de la Porte Molitor",
"de la Porte Pouchet",
"de la Porte d'Asnières",
"de la Porte d'Aubervilliers",
"de la Porte d'Auteuil",
"de la Porte d'Italie",
"de la Porte d'Ivry",
"de la Porte d'Orléans",
"de la Porte de Bagnolet",
"de la Porte de Champerret",
"de la Porte de Charenton",
"de la Porte de Choisy",
"de la Porte de Châtillon",
"de la Porte de Clichy",
"de la Porte de Clignancourt",
"de la Porte de Montmartre",
"de la Porte de Montreuil",
"de la Porte de Montrouge",
"de la Porte de Ménilmontant",
"de la Porte de Pantin",
"de la Porte de Plaisance",
"de la Porte de Saint Cloud",
"de la Porte de Saint Ouen",
"de la Porte de Sèvres",
"de la Porte de Vanves",
"de la Porte de Villiers",
"de la Porte de Vincennes",
"de la Porte de Vitry",
"de la Porte de la Chapelle",
"de la Porte de la Plaine",
"de la Porte de la Villette",
"de la Porte des Lilas",
"de la Porte des Poissonniers",
"de la Porte des Ternes",
"de la Porte du Pré Saint Gervais",
"de la Pyramide",
"de la Pépinière",
"de la Reine Marguerite",
"de la République",
"de la Seine à Bagatelle",
"de la Sibelle",
"de la Sœur Rosalie",
"de la Tunisie",
"des Arts",
"des Bouleaux",
"des Buttes",
"des Canadiens",
"des Cascades",
"des Champs Élysées",
"des Chasseurs",
"des Dames",
"des Eiders",
"des Fortifications",
"des Frères Voisin",
"des Gobelins",
"des Hortensias",
"des Justes de France",
"des Lacs à la Porte Dauphine",
"des Lapins",
"des Minimes",
"des Nations Unies",
"des Pavillons",
"des Peupliers",
"des Portugais",
"des Poteaux",
"des Pépinières",
"des Quatre Carrefours",
"des Refuzniks",
"des Réservoirs",
"des Sycomores",
"des Ternes",
"des Terroirs de France",
"des Tilleuls",
"des Tribunes",
"des Vergers",
"des Vieux Chênes",
"des Écoles",
"des Érables",
"du 22 Novembre 1943",
"du 8 Février 1962",
"du 8 novembre 1942",
"du Bataillon Français de l'ONU en Corée",
"du Bataillon du Pacifique",
"du Bel Air",
"du Belvédère",
"du Bord de l'Eau",
"du Bout des Lacs",
"du Brésil",
"du Caire",
"du Calvaire",
"du Canada",
"du Capitaine Dronne",
"du Cardinal Amette",
"du Cardinal Lavigerie",
"du Carrousel",
"du Chancelier Adenauer",
"du Chef d'Escadron de Guillebon",
"du Château Rouge",
"du Châtelet",
"du Cimetière",
"du Cimetière des Batignolles",
"du Colonel Bonnet",
"du Colonel Bourgoin",
"du Colonel Fabien",
"du Colonel Henri Rol Tanguy",
"du Commandant Raynal",
"du Commerce",
"du Comtat Venaissin",
"du Coq",
"du Dix Huit Juin 1940",
"du Dix Neuf Mars 1962",
"du Docteur Alfred Fournier",
"du Docteur Antoine Béclère",
"du Docteur Arnold Netter",
"du Docteur Brouardel",
"du Docteur Félix Lobligeois",
"du Docteur Gley",
"du Docteur Hayem",
"du Docteur Lannelongue",
"du Docteur Navarre",
"du Docteur Paul Michaux",
"du Docteur Yersin",
"du Guatemala",
"du Guignier",
"du Général Balfourier",
"du Général Beuret",
"du Général Brocard",
"du Général Catroux",
"du Général Clavery",
"du Général Cochet",
"du Général Denain",
"du Général Dodds",
"du Général Dubail",
"du Général Détrie",
"du Général Eisenhower",
"du Général Ferrié",
"du Général Gouraud",
"du Général Ingold",
"du Général Jacques Pâris de Bollardière",
"du Général Koenig",
"du Général Laperrine",
"du Général Leclerc",
"du Général Lemonnier",
"du Général Maistre",
"du Général Mangin",
"du Général Marguerite",
"du Général Messimy",
"du Général Michel Bizot",
"du Général Monclar",
"du Général Patton",
"du Général San Martin",
"du Général Sarrail",
"du Général Stefanik",
"du Général Tessier de Marguerittes",
"du Général Tripier",
"du Général de Gaulle",
"du Havre",
"du Lieutenant Henri Karcher",
"du Lieutenant Stéphane Piobetta",
"du Louvre",
"du Mahatma Gandhi",
"du Maine",
"du Maquis du Vercors",
"du Marché Sainte Catherine",
"du Maroc",
"du Maréchal Fayolle",
"du Maréchal Franchet d'Espérey",
"du Maréchal Gallieni",
"du Maréchal Juin",
"du Maréchal Lyautey",
"du Maréchal Maunoury",
"du Maréchal de Lattre de Tassigny",
"du Nicaragua",
"du Nouveau Conservatoire",
"du Onze Novembre 1918",
"du Palais Bourbon",
"du Palais Royal",
"du Panthéon",
"du Paraguay",
"du Parc de Charonne",
"du Parc de Choisy",
"du Parc de Passy",
"du Parc des Princes",
"du Pavillon d'Armenonville",
"du Polygone",
"du Pont Neuf",
"du Professeur André Lemierre",
"du Professeur Jean Bernard",
"du Préfet Claude Erignac",
"du Président Kennedy",
"du Président Mithouard",
"du Président Wilson",
"du Président Édouard Herriot",
"du Puits de l'Ermite",
"du Père Chaillet",
"du Père Julien Dhuit",
"du Père Lachaise",
"du Père Marcellin Champagnat",
"du Père Teilhard de Chardin",
"du Pérou",
"du Québec",
"du Ranelagh",
"du Recteur Poincaré",
"du Révérend Père Michel Riquet",
"du Square",
"du Tertre",
"du Tremblay",
"du Trocadéro et du 11 Novembre",
"du Trône",
"du Vingt Cinq Août 1944",
"du Vénézuela",
"Édith Piaf",
"Édouard Renard",
"Édouard VII",
"Édouard Vaillant",
"Élisabeth Dmitrieff",
"Élisée Reclus",
"Émile Acollas",
"Émile Bergerat",
"Émile Deschanel",
"Émile Goudeau",
"Émile Landrin",
"Émile Laurent",
"Émile Mâle",
"Émile Pouvillon",
"Émile Zola",
"Émile et Armand Massard",
"Étienne Pernet"
);

//tab villes
$tabVilles = array(
  "Nantes",
  "Rezé",
  "Saint Sébastien sur Loire",
  "Bouguenais",
  "Lyon",
  "Villeurbanne",
  "Ecully",
  "Bordeaux",
  "Le Bouscat",
  "Cenon",
  "Talence",
  "Bègles"
);



// Tableau des villes et codes postaux associés :
$tabVilleCP = array(
  "Nantes"                    => $cp=array(44000, 44100, 44200, 44300),
  "Rezé"                      => $cp=array(44400),
  "Saint Sébastien sur Loire" => $cp=array(44230),
  "Bouguenais"                => $cp=array(44340),

  "Lyon"                      => $cp=array(69001, 69002, 69003, 69004, 69005, 69006, 69007, 69008, 69009),
  "Villeurbanne"              => $cp=array(69100),
  "Ecully"                    => $cp=array(69130),

  "Bordeaux"                  => $cp=array(33000, 33100, 33200, 33300, 33800),
  "Le Bouscat"                => $cp=array(33110),
  "Cenon"                     => $cp=array(33150),
  "Talence"                   => $cp=array(33400),
  "Bègles"                    => $cp=array(33130)
);

// Tableau des codes-villes :
$tabCodesVillesUFR = array(
  "NTE" => "Nantes",
  "SNZ" => "Saint Nazaire",
  "REN" => "Rennes"
);

// Tableau des UFR de Nantes/Saint Nazaire/Rennes :
$tabUniversites = array(
  "DSP" => "UFR de droit et de sciences politiques",
  "LNG" => "UFR de langues et cultures étrangères",
  "MED" => "UFR de médecine et techniques médicales",
  "SCI" => "UFR de sciences et techniques",
  "HIS" => "UFR d’histoire",
  "LET" => "UFR lettres et langue"
);

// Tableau des rapartitions UFR/villes :
$tabRepartitionUFRVille = array(
  "NTE" => array("DSP", "LNG", "MED", "SCI", "HIS", "LET"),
  "SNZ" => array("DSP", "LNG", "MED", "SCI", "HIS", "LET"),
  "REN" => array("DSP", "LNG", "MED", "SCI", "HIS", "LET")
);

// Tableau des cours par UFR :
$tabCoursUFR = array(
  "DSP" => array("Droit général", "Droit des affaires", "Droit notarial", "Droit privé général"),
  "LNG" => array("Anglais", "Arabe", "Allemand", "Italien", "Russe", "Espagnol", "Polonais", "Portugais"),
  "MED" => array("Cancérologie", "Someil", "Pédiatrie", "Cardiologie", "Neurologie", "Gérontologie", "Oncogériatrie"),
  "SCI" => array("Chimie", "Mathématiques", "Physique", "Informatique", "Sciences de la vie", "Sciences de la Terre et de l'Univers"),
  "HIS" => array("Médiévale", "Ancienne", "Contemporaire", "Moderne", "Mondiale"),
  "LET" => array("Lettres Anciennes", "Lettres Modernes", "Lettres Classiques", "Philosophie", "Latin", "Grec ancien")
);

// Tableau des livres par UFR :
$tabLivresUFR = array(
  "DSP" => array("Traité de Droit général", "Traité de Droit des affaires", "Traité de Droit notarial", "Traité de Droit privé général"),
  "LNG" => array("Apprendre l'Anglais", "Apprendre l'Arabe", "Apprendre l'Allemand", "Apprendre l'Italien", "Apprendre le Russe", "Apprendre l'Espagnol", "Apprendre le Polonais", "Apprendre le Portugais"),
  "MED" => array("Comprendre la Cancérologie", "Comprendre le Someil", "Comprendre la Pédiatrie", "Comprendre la Cardiologie", "Comprendre la Neurologie", "Comprendre la Gérontologie", "Comprendre l'Oncogériatrie"),
  "SCI" => array("Traité de Chimie", "Traité de Mathématiques", "Traité de Physique", "Traité d'Informatique", "Traité des Sciences de la vie", "Traité des Sciences de la Terre et de l'Univers"),
  "HIS" => array("Histoire Médiévale", "Histoire Ancienne", "Histoire Contemporaire", "Histoire Moderne", "Histoire Mondiale"),
  "LET" => array("Introduction aux Lettres Anciennes", "Introduction aux Lettres Modernes", "Introduction aux Lettres Classiques", "Introduction à la Philosophie", "Introduction au Latin", "Introduction au Grec ancien")
);
?>
